FROM debian:stable-slim
MAINTAINER Todor Gitchev <todor.gitchev@gmail.com>

ENV DEBIAN_FRONTEND=noninteractive

# install all 
RUN apt-get update --yes
RUN apt-get install --yes gcc
RUN apt-get install --yes gfortran
RUN apt-get install --yes cmake
RUN apt-get install --yes openmpi-bin openmpi-doc libopenmpi-dev
RUN apt-get install --yes libhdf5-dev libhdf5-openmpi-dev
RUN apt-get install --yes curl
RUN apt-get install --yes python3-pip
RUN apt-get install --yes python3-venv
RUN curl -LsSf https://astral.sh/uv/install.sh | env UV_INSTALL_DIR="/opt/uv" sh
RUN echo "PATH=$PATH:/opt/uv" >> ~/.bashrc
#RUN curl -LsSf https://astral.sh/uv/install.sh | sh   #
#RUN chmod +x Mambaforge-Linux-x86_64.sh
#RUN bash ./Mambaforge-Linux-x86_64.sh -b -p /opt/mambaforge

# check all is there
CMD gcc --version
CMD gfortran --version
CMD cmake --version
CMD mpirun --version
CMD h5cc -showconfig
#CMD mamba list
CMD python --version
CMD pip --version
#CMD uv --version
# CMD locate mpirun

# need to be in the
#CMD echo "PATH=$PATH:/opt/uv" >> ~/.bashrc
#CMD source ~/.bashrc
